version: "3.9"
services:
  unify:
   build: ./Unify-frontend
   ports:
     - "8080:3000"
   volumes:
     - ./Unify-frontend:/Unify-react
   
  unifymid:
    build: ./Unify-backend
    ports:
     - "8081:3000"
    volumes:
      - ./Unify-backend:/code
    command: ["./wait-for-it.sh", "db:27017", "--", "npx", "nodemon"]
  db:
    image: mongo:latest
